### ISSUE TITLE
CSS中选择器的特殊性---样式匹配的优先级 

### ISSUE THREAD

**Issue by lorelei47** [lorelei47/StudyDiary#1]
#### 选择器的特殊性
选择器的特殊性由选择器组件确定，特殊性的值结构为：0 0 0 0。

```css
p { color: red} //p为选择器的组件
div p {color: blue} // div p为选择器组件
```
---
#### 特殊性的规则
* 各个ID的特殊性值：0 1 0 0
* 各个类、属性、伪类的特殊性值：0 0 1 0
* 各个元素、伪元素的特殊性值：0 0 0 1
* 通配选择器*的特殊性值为0，即： 0 0 0 0

```css
.header { color: red} // 0 0 1 0 
div.header {color: blue} // 0 0 1 1 
.main div#title { color: red} // 0 1 1 1
div.mian p#title {color: blue} // 0 1 1 2 
```
特殊性值会根据组件的构成，确定选择器的特殊性值。

---
#### 选择器的比较规则与匹配优先级
特殊性值结构大小很简单，跟进制的大小类同，比如：
* 以0 1 开头的比所有以0 0开头的都大： 0 1 0 0 > 0 0 1 1 ;
* 相同开头则比较位的大小： 0 0 1 5 < 0 0 2 1

因此，对于匹配相同对象css属性值的选择器时，元素显示哪个选择器的样式，只需比较选择器特殊性的大小即可。
```css
<div class="main">
    <p  id="header" class="title">hello world</p>
</div>
div p.title {color: red} // 0 0 1 2
p#header {color: blue} // 0 1 0 1
```
在上面这个例子中，两个选择器都设定了color值，但由于第二个选择器的特殊性值大，因此最终p元素里面的hello world显示了blue蓝色。

---
#### 内联样式的特殊性
特殊性值： 1 0 0 0预留了给内联样式。
内联样式即在元素标签中使用style属性设置的css属性值。
因此内联样式的优先级会高于上述所说的三种。

```css
<div class="main">
    <p  id="header" class="title" style=“color: yellow”>hello world</p>
</div>
div p.title {color: red} // 0 0 1 2
p#header {color: blue} // 0 1 0 1
```

上述例子中设置了内联样式，因此最终p元素里面的hello world显示了yellow黄色。

---
#### 相同特殊性的情况
样式匹配规则除了特殊性，还有有顺序，来源，权重，以及重要性。
因此，这里仅介绍了样式匹配规则中的其中一个--选择器的特殊性。在实际应用中还需要结合其他规则应用。
